version: '3'
services:
  app:
    build: .
    ports:
      - "5003:5003"
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=yourkey
      - WEATHER_API_KEY=yourkey
      - CITY_NAME=Chicago
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge